# Can we use exception in a class

class XYZ:
    def f1(self):
        try
            a
